version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - type: Group
      instructions:
        - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"
      enable_if:
        condition: property
        property: host.os
        equals_value: Linux

  Test:
    - type: Group
      instructions:
        - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
      enable_if:
        condition: and
        conditions:
          - condition: property
            property: host.os
            equals_value: Linux
          - condition: property
            property: host.os
            equals_property: target.os
          - condition: property
            property: target.osVersion
            not_equals_value: QEMU
